//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SafeHome360
{
    using System;
    using System.Collections.Generic;
    
    public partial class history
    {
        public int Id { get; set; }
        public string message { get; set; }
        public Nullable<int> status { get; set; }
        public string date { get; set; }
        public string Button { get; set; }
    }
}
